// <auto-generated />
using EgitimPortali.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EgitimPortali.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241207160936_mig1")]
    partial class mig1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EgitimPortali.Models.Education", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Educations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Eğitim",
                            IsActive = true,
                            Name = "Eğitim1"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Eğitim açıklama",
                            IsActive = true,
                            Name = "Eğitim2"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Eğitim açıklama",
                            IsActive = false,
                            Name = "Eğitim3"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Eğitim açıklama",
                            IsActive = false,
                            Name = "Eğitim4"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Eğitim açıklama",
                            IsActive = false,
                            Name = "Eğitim5"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
